CREATE DATABASE MODUL7;
USE MODUL7;

CREATE TABLE FAKULTAS (
	ID_FAKULTAS SMALLINT PRIMARY KEY,
	FAKULTAS VARCHAR(45)
);

CREATE TABLE JURUSAN (
	ID_JURUSAN SMALLINT PRIMARY KEY,
	ID_FAKULTAS SMALLINT REFERENCES FAKULTAS(ID_FAKULTAS),
	JURUSAN VARCHAR(45)
);

CREATE TABLE STRATA (
	ID_STRATA SMALLINT PRIMARY KEY,
	SINGKAT VARCHAR(10),
	STRATA VARCHAR(45)
);

CREATE TABLE PROGRAM_STUDI (
	ID_PROGRAM_STUDI SMALLINT PRIMARY KEY,
	ID_STRATAS SMALLINT REFERENCES STRATA(ID_STRATA),
	ID_JURUSAN SMALLINT REFERENCES JURUSAN(ID_JURUSAN),
	PROGRAM_STUDI VARCHAR(60)
);

CREATE TABLE SELEKSI_MASUK (
	ID_SELEKSI_MASUK SMALLINT PRIMARY KEY,
	SINGKAT VARCHAR(12),
	SELEKSI_MASUK VARCHAR(60)
);

CREATE TABLE MAHASISWA (
	NIM VARCHAR(15) PRIMARY KEY,
	ID_SELEKSI_MASUK SMALLINT REFERENCES SELEKSI_MASUK(ID_SELEKSI_MASUK),
	ID_PROGRAM_STUDI SMALLINT REFERENCES PROGRAM_STUDI(ID_PROGRAM_STUDI),
	NAMA VARCHAR(45),
	ANGKATAN SMALLINT,
	TGL_LAHIR DATE,
	KOTA_LAHIR VARCHAR(60),
	JENIS_KELAMIN CHAR(1) CHECK(JENIS_KELAMIN IN ('W','P'))
);

INSERT INTO FAKULTAS VALUES
(1,'Ekonomi & Bisnis'),
(2,'Ilmu Komputer');

INSERT INTO JURUSAN VALUES
(21,2,'Informatika'),
(22,2,'Sistem Informasi'),
(23,2,'Teknik Komputer');

INSERT INTO STRATA VALUES
(1,'D1','Diploma'),
(2,'S1','Sarjana'),
(3,'S2','Magister');

INSERT INTO PROGRAM_STUDI VALUES
(211,2,21,'Teknik Informatika'),
(212,2,21,'Teknik Komputer'),
(219,3,21,'Magister Ilmu Komputer');

INSERT INTO SELEKSI_MASUK VALUES
(1,'SNMPTN','SELEKSI NASIONAL MAHASISWA PERGURUAN TINGGI NEGERI'),
(2,'SBMPTN','SELEKSI BERSAMA MAHASISWA PERGURUAN TINGGI NEGERI');
 
INSERT INTO MAHASISWA VALUES 
('155150400',1,211,'JONI',2015,'1997-1-1','Malang','W'),
('155150401',2,212,'JONO',2015,'1997-10-2','Situbondo','P'),
('155150402',2,211,'JONATHAN',2016,'1997-11-1','Magelang','W');

UPDATE MAHASISWA SET NAMA = 'RIVALDO SIDIQ PRADANA', NIM = '225150600111026', ID_PROGRAM_STUDI = 219, ANGKATAN = 2022, TGL_LAHIR = '2004-1-23', KOTA_LAHIR = 'Wonogiri', JENIS_KELAMIN = 'W'  WHERE NIM = '155150400';

DELETE FROM MAHASISWA WHERE ID_SELEKSI_MASUK = 2;

SELECT * FROM MAHASISWA;